//cookie与session的区别
//cookie把用户的重要信息发送给浏览器，浏览器进行保存，cookie把数据保存在客户端
//session技术，它是针对用户的请求，在服务端创建一个对象，然后吧用户请求重要数据保存在服务器端创建的这个对象中


//客户端第一次请求服务器，
//服务器的内部调用getSession的方法获取当前基于这个客户端的浏览器的那个session对象，第一次请求肯定没有session对象，服务器内部会创建这个session对象
//在服务器的内部创建session的时候，会给每一个session绑定一个id数据（jsessionid），所有的客户端浏览器在服务器的session的id都不会相同
//服务器会将jsessionid作为cookie的信息写给客户端
//客户端再次请求，就会自动携带jsessionid的cookie信息到服务器
//根据cookie中的jsessionid获取当前这个浏览器的唯一对应的那个session对象

//有多少个客户端请求服务器，服务器就要创建多少个session对象，每一个浏览器客户端都有一个session对象，导致服务端会有很多的session对象（一个浏览器独占一个session对象，默认情况下），所以session在服务器有存活时间

//服务器端可以识别每一个用户的session对象，是因为服务器针对每一个用户都发送key为jsessionid的cookie信息。
//用户在操作的时候，都会携带这个cookie到服务器端，服务器才能识别针对当前这个jsessionid的那个session对象。

//关于浏览器关闭之后session还能用么？
//服务器在给客服端响应数据的时候，把session对象的jsessionid作为cookie的key值发送给浏览器
//这个cookie是一个会话级别（临时）cookie，他只能在浏览器运行的阶段存活。
//如果游览器关闭了，cookie信息就没有了，再次打开浏览器访问的时候，服务器就获取不到针对当前用户的jsessionid信息，无法找到针对当前用户的那个session对象了
//答：可以在服务端servlet，手动的将保存jsessionid的cookie给持久化，这样可以保证关闭浏览器之后，再次打开，依然有jsessionid的存在，那么服务器的session还是继续可以使用。